name: input stuff

on:
  workflow_dispatch:
    inputs:
      first:
        description: "A field"
        required: true
        default: "field1val"
        
jobs:
  say_hello:
    runs-on: self-hosted
    steps:
    - name: print some things
      run: |
        echo "Hello $!"
        echo "boop"
